Неограниченная и быстрая история просмотров
Jarami/java-kanban pull request #1
Opened 2024-07-31 13:38 UTC by Jarami

Добавлена функциональность по спринту 6:
1. Сделать историю посещений неограниченной по размеру.
2. Избавиться от повторных просмотров в истории. Если какую-либо задачу посещали несколько раз, то в истории должен остаться только её последний просмотр. Предыдущий должен быть удалён.

2024-07-31 15:08 UTC, andrew-larkin requested changes
Привет! Отличная реализация и отличное покрытие тестами! Есть одно предложение, если есть время, рекомендую его выполнить.

2024-07-31 15:08 UTC, andrew-larkin commented on src/managers/InMemoryHistoryManager.java
> +        return tasks.getTasks();
хорошо было бы сделать, чтобы список просмотров начинался с последней просмотренной задачи. То есть порядок элементов в списке "по свежести".

2024-07-31 17:23 UTC, Jarami commented on src/managers/InMemoryHistoryManager.java
> +        return tasks.getTasks();
Сделано

2024-08-01 06:18 UTC, andrew-larkin approved these changes
Отлично, работа принята!

2024-08-14 10:51 UTC, merged