Create FileBackedTaskManager
Jarami/java-kanban pull request #2
Opened 2024-08-16 13:13 UTC by Jarami

Добавил менеджера задач с сохранением в файл.

2024-08-18 08:38 UTC, andrew-larkin requested changes
Привет! Отличная работа, все работает как часы! Всего одна небольшая проблема - ее реализовать и работа будет принята.

2024-08-18 08:38 UTC, andrew-larkin commented on src/managers/FileBackedTaskManager.java
> +    private static Task fromString(String line) {
этот и другие методы парсинга стоит сделать статическими и выделить в отдельный класс, например, CSVFormat. Это разгрузит текущий класс менеджера от доп. логики

2024-08-19 07:03 UTC, Jarami commented on src/managers/FileBackedTaskManager.java
> +    private static Task fromString(String line) {
Создал класс CSVFormat.

2024-08-19 17:15 UTC, andrew-larkin approved these changes
Привет! Отлично, работа принята!

2024-09-04 09:22 UTC, merged