Sprint 8 solution time and duration
Jarami/java-kanban pull request #3
Opened 2024-09-09 09:26 UTC by Jarami

Добавил задачам продолжительность, время старта, и возвращение списка по приоритету (времени начала)

2024-09-09 21:16 UTC, andrew-larkin requested changes
Привет! Отличная работа! Качественная реализация нового функционала и тестов, много удачных решений. Остается местами внести несколько некритичных правок и работа будет принята.

2024-09-09 21:16 UTC, andrew-larkin commented on src/managers/InMemoryTaskManager.java
> +    private final Set<Task> prioritizedTasks = new TreeSet<>(Comparator.comparing(Task::getStartTime));
отлично!

2024-09-09 21:16 UTC, andrew-larkin commented on src/managers/InMemoryTaskManager.java
> +        Optional<Epic> maybeEpic = epicRepo.findById(id);
maybeEpic - не совсем подходящее название. можно назвать просто epic

2024-09-09 21:16 UTC, andrew-larkin commented on src/tasks/Epic.java
> +        this(null, name, description, TaskStatus.NEW, null, null);
duration и startTime можно установить как дефолтные значения. типа начало - сейчас, длительность - 5 минут

2024-09-09 21:16 UTC, andrew-larkin commented on test/managers/FileBackedTaskManagerTest.java
> +//    private TaskManager manager;
закомментированный код удаляем

2024-09-10 06:25 UTC, Jarami commented on src/tasks/Epic.java
> +        this(null, name, description, TaskStatus.NEW, null, null);
Можно. Но в ТЗ этого не сказано. А еще сказано, что "Дата начала задачи по каким-то причинам может быть не задана."

2024-09-10 20:14 UTC, andrew-larkin commented on src/tasks/Epic.java
> +        this(null, name, description, TaskStatus.NEW, null, null);
да, согласен, оставляй как есть

2024-09-11 17:25 UTC, andrew-larkin approved these changes
Отлично, работа принята!

2024-09-14 18:40 UTC, merged